---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps.fixnops.com
  resources:
  - platformapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.fixnops.com
  resources:
  - platformapps/status
  verbs:
  - get
  - patch
  - update
